- name: "Instalacion"
  apt:
    pkg:
      - isc-dhcp-server
      - iptables
- name: "/etc/network/interfaces"
  template:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
  notify:
    - reiniciar servidor

- name: "forwarding"
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    
- name: "Plantilla de /etc/dhcp/dhcpd.conf"
  template:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - reiniciar dhcp

- name: "Plantilla de /etc/default/isc-dhcp-server"
  template:
    src: isc-dhcp-server
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: '0644'
  notify:
    - reiniciar dhcp
